In [3]:
import pandas as pd

In [4]:
def what_type_of_data(df:pd.DataFrame):
    num_cols=df.select_dtypes(include='number').columns.tolist()
    cat_cols=df.select_dtypes(exclude='number').columns.tolist()
    return num_cols,cat_cols

In [5]:
dataset=pd.read_csv('exemple.csv')

In [6]:
dataset

    number  twice  three_times
0        6     12           18
1        7     14           21
2        8     16           24
3        9     18           27
4       10     20           30
5       11     22           33
6       12     24           36
7       13     26           39
8       14     28           42
9       15     30           45
10      16     32           48
11      17     34           51
12      18     36           54
13      19     38           57
14      20     40           60

In [9]:
n,c=what_type_of_data(dataset)

In [11]:
dataset[c]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]